import type { Metadata } from "next"
import { Alegreya_Sans } from "next/font/google"
import "./globals.css"

const alegreya = Alegreya_Sans({
  weight: ["300", "500", "700"],
  variable: "--font-alegreya",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={alegreya.className}>{children}</body>
    </html>
  )
}
