// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about: dynamic(() => import("./About")),
  faqs: dynamic(() => import("./Faqs")),
  feature: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  trips: dynamic(() => import("./Trips")),
}
