// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about: dynamic(() => import("./About")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_info: dynamic(() => import("./ContactInfo")),
  faqs: dynamic(() => import("./Faqs")),
  feature: dynamic(() => import("./Features")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  trips: dynamic(() => import("./Trips")),
}
